file: "src/main/resources/textures/default.jpg"
step: 0.0625
blocks:
  air:
    test: "ciao"
    id: 0
  dirt:
    id: 1
    textures:
      top:
        x: 2
        y: 0
      bot:
        x: 2
        y: 0
      left:
        x: 2
        y: 0
      right:
        x: 2
        y: 0
      front:
        x: 2
        y: 0
      back:
        x: 2
        y: 0
  stone:
    id: 2
    textures:
      top:
        x: 1
        y: 0
      bot:
        x: 1
        y: 0
      left:
        x: 1
        y: 0
      right:
        x: 1
        y: 0
      front:
        x: 1
        y: 0
      back:
        x: 1
        y: 0
  grass:
    id: 3
    textures:
      top:
        x: 5
        y: 0
      bot:
        x: 2
        y: 0
      left:
        x: 3
        y: 0
      right:
        x: 3
        y: 0
      front:
        x: 3
        y: 0
      back:
        x: 3
        y: 0
  water:
    id: 4
    textures:
      top:
        x: 14
        y: 0
      bot:
        x: 14
        y: 0
      left:
        x: 14
        y: 0
      right:
        x: 14
        y: 0
      front:
        x: 14
        y: 0
      back:
        x: 14
        y: 0